### ISSUE TITLE
Evaluation of cognitive ability idea related to AOI

### ISSUE THREAD

**Issue by Adrieennn** [GazePlay/GazePlay#1100]
The idea is to analyses the pattern of eye gaze to have an idea of the player's cognitive processing strategies thus to evaluate one's cognitive ablity.

In the paper they used a matrix completion task, a very logic and reasoning related task. They defined 3 types of event: 
Encoding: an atomic gaze pattern(scan throw a row or column) relating to the understanding of a rule.
Integration: several encoding event back to back, means integration of multiple rule of the game.
Toggle: switch between the game configuration and  answer area.

They found out that the number occurrence for encoding event and integration event during is related to the performance category of the child. This could be an entry point we can use the evaluate the cognitive ability. However we have to implement the Top down model of AOI in the game to make this work. 

See paper here [Aiming to Complete the Matrix: Eye-Movement Analysis of Processing Strategies in Children's Relational Thinking](https://www.researchgate.net/publication/301937970_Aiming_to_Complete_the_Matrix_Eye-Movement_Analysis_of_Processing_Strategies_in_Children's_Relational_Thinking)

**Comment by schwabdidier** [comment]
What are the differences/links with @Sannaraek's work ?

**Comment by Sannaraek** [comment]
Hi

This is a brief summary of more or less what I did that's similar to your suggestion 

So I did something similar to what you said stated, I called it the Target AO (Maybe there is a formal naming convention but I don't know it.)  Its main purpose is to measure the improvements of the user's cognitive ability. Initially, I spoke with professor Didier, We agreed that GazePlay also aims to help players get more familiarised with HCI means, specifically with eye trackers. 

For me, The Target AOI can be defined in 2 different ways. 
We can establish Target AOI with the AOIs of users with the highest score when they play a game (This is an easy but less accurate way, Where we simply save a good user's AOI as the target AOI's for the next game instance). This is already implemented but I didn't have time to fully optimize & test this because it was at the end. Soo a lot of improvements can be made upon

Another method is as you say, we can pre-define the "optimal" Target AOI based on the context of the game. ("Say for biboule jump, the next optimal Target AOI would be somewhere near the clouds the user has to jump to). This is a more accurate but more intensive approach to implement where you need to specifically define an optimal Target AOI for each game, A general framework "maybe" possible for Gazeplay but I haven't thought about this yet.

The Target AOI works as a bounding box. We measure out of User's AOI's, how many of them are within the Target AOI's bounding box. We measure the user's cognitive ability performance/improvement according to this. A score is generated at the end of this.

There's a lot of work that can be continued from this, good luck!

**Comment by schwabdidier** [comment]
Wow, thank you very much for your answer @Sannaraek  !
