### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by PillouMatou** [GazePlay/GazePlay#1133]
**Describe the bug**
When I play more than 5 minutes to a game with images like creampies my GazePlay crash

**To Reproduce**
1. Play a game like creampies and retry until the bug happen
2. at the screen with results the bug happen
3. See error in the console

**Expected behavior**
We should can play without a crash because we are out of memory

**Screenshots**
![memory](https://user-images.githubusercontent.com/43779207/76544311-18a4ba00-6488-11ea-9065-48e0ae6a49ec.png)

**Context:**
 - OS: [Windows 7]
 - Java Version: the lastest
 - GazePlay Version: 1.7.2

**Additional context**

**Comment by kuhlkrein** [comment]
Sometimes in GazePlay we have some out of memory error, I wanted to check why this happened, and it seems that some object are still in the memory event when we remove them from the gameContext. We have to find a way to really delete it if we want to avoid this problem.
As you can see here the number of target in memory is equal to the 6 on the screen + the 45 already shooted:

![image](https://user-images.githubusercontent.com/24478346/77426807-8aa8c780-6dd5-11ea-84f1-5ba42dcbf1eb.png)

So the object are still in memory while they will not be used anymore. It could be due to the fact that we're not removing events (gaze and mouse events) linked to these objects for exemple.
