### ISSUE TITLE
SpaceGame bug between System.gc() and Graddle

### ISSUE THREAD

**Issue by PillouMatou** [GazePlay/GazePlay#1183]
**Describe the bug**
When we put the function System.gc() in the code, Graddle block this content.

**To Reproduce**
1. Go to SpaceGame.java
2. decomment System.gc();
3. do a PR
4. See error on github

**Expected behavior**
The graddle test should be successful.

**Context:**
 - OS: Windows 10
 - Java Version: 11.0.5
 - GazePlay Version: Lastest

**Comment by Tohaker** [comment]
Can you point out the line that `System.gc()` is being called? I can't find it in the latest `develop` files. 
In any case - we should never be invoking the GC ourselves. There's no guarantee that it will even run, and it implies that we know better than the JVM (we don't). To better handle memory, we should be descoping variables as early as possible, which will queue them up to be garbage collected.

**Comment by PillouMatou** [comment]
`System.gc()` is called in my Pull request : Updates space game #1180.
I called this function to the lines : 526, 664, 715.

**Comment by Tohaker** [comment]
Well the reason that build failed was spotbugs. If I were to make a guess (since I can't see in the pipeline why spotbugs failed), I would say that it's preventing you from calling the GC manually as I explained above. If you really need garbage collection to make this game work, this isn't the right way to do it.
