### ISSUE TITLE
Error in the GameSpec.java file

### ISSUE THREAD

**Issue by PillouMatou** [GazePlay/GazePlay#1186]
**Describe the bug**
There are 2 functions with the same name 'IntListVariantGenerator'

**To Reproduce**
1. Go to 'gazeplay-games-commons\src\main\java\net\gazeplay'
2. Open 'GameSpec.java'
3. Scroll down to 'public IntListVariantGenerator(final String variantChooseText, final int... values)'

**Expected behavior**
we shouldn't have an error in our file.

**Screenshots**
![bug](https://user-images.githubusercontent.com/43779207/82305811-72f95400-99be-11ea-8529-b2f9c54972e4.png)

**Context:**
OS: Windows 10
Java Version: 11.0.5
GazePlay Version: Lastest

**Comment by Tohaker** [comment]
This appears to be due to the use of `@Data`, which [tells Lombok to generate an all args constructor for us](https://projectlombok.org/features/Data). This doesn't actually cause us any build errors, though we can solve this 'error' in two ways; 
1. Remove the manually defined constructor and change the usages of it to use `int[]` arrays rather than Varargs.
2. Remove `@Data` and replace it with `@ToString` and `@EqualsAndHashCode`, with `@Getter` and `@Setter` on each variable in the class.
