### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by Noars** [GazePlay/GazePlay#1287]
Display a menu bar with for each entry a game category and which lists the corresponding games + be able to launch the chosen game from this menu.
Add a checkbox to select/unselect everything

**Comment by schwabdidier** [comment]
I don't understand

**Comment by Philippe-meylan** [comment]
It's an additionnal and easy way to show and activate the games.
Rather than having a list of game categories as it is now, we propose to have a menu with an entry for each category.
When you select an entry in the menu, a list of all the games corresponding to the category is displayed.
If you select a name in this list, the game is started.
The additionnal checkbox (select all/unselect all) is used with the search function.

**Comment by schwabdidier** [comment]
still to do ?

**Comment by schwabdidier** [comment]
still to do ?
