### ISSUE TITLE
colored bubble : game variant

### ISSUE THREAD

**Issue by PillouMatou** [GazePlay/GazePlay#1419]
In the game variant, the variant without fix a bubble to destroy it didn't work like this, in this variant we have to fix the bubble too.
We shouldn't have to fix the bubble in this game variant.

**Comment by Iluvrog** [comment]
#1429

**Comment by kuhlkrein** [comment]
@schwabdidier For this one, if I remember well, the point at the very beginning was to create bubbles that are growing and then explode. But don't you think that it can still be relevant to be able to adapt the fixation lentgh for both variants (like in ninja).
If it's not the case then we should maybe merge the 2 variants, and make the bubble grow when the fixation lentgh is > 0, and just make it explode when it's == 0 ?

**Comment by kuhlkrein** [comment]
@PillouMatou @Iluvrog what do you think ?

**Comment by Iluvrog** [comment]
> @PillouMatou @Iluvrog what do you think ?

Maybe, it's simpler if we merge the two variants but it's less fun if the player has to change the parameters each time he wants to play this game. Do what you think is the best

**Comment by kuhlkrein** [comment]
We talked with @schwabdidier about this, and what we conclude is that we keep two separated variants, 
but for the "fix" variant we're displaying bubbles randomly on the screen and they are not moving (so that it's easier to fix),
 also the "game speed" will become the speed of the bubble appearance in this variant

**Comment by Iluvrog** [comment]
@kuhlkrein it's done
