### ISSUE TITLE
The project lacks of documentation

### ISSUE THREAD

**Issue by WaffleBuffer** [GazePlay/GazePlay#169]
There is a lack of documentation in the project. What do the code ? What are the specs of the interface ? etc.
Also, some commentary about animation to know what a bunch of animation code do ("//rotate the image" for example).
Finally, don't forget JavaDoc. This is useful to know what a function wait as input and what we could have as output (what do we have when there is an internal error ? What kind of exception could be raised and why ?).

**Comment by YannRobert** [comment]
About JavaDoc and code comments : 
I prefer self-explanatory code, over code comments that will eventually rot, because let's face it, it won't be kept up-to-date with the code.

Refactor the code until it's so easy to read that any documentation is useless.

Still, some more documentation on many other things would still be useful.

**Comment by Tohaker** [comment]
We're in a good place with documentation, so I'll close this for now
