### ISSUE TITLE
problem with ressources

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#897]
We don't have anymore ressources in the gazeplay-data folder.

Everything is only in the build folder. It is a bug isn't it ?

**Comment by schwabdidier** [comment]
@Tohaker ?

**Comment by Tohaker** [comment]
Sorry for the delay, Github notifications are still not coming through for me. 
This isn't a bug, its part of my last PR. Resources were removed from gazeplay-data as it was causing bugs when running as a released version. 
The intention is to have all resources in the proper Java locations, and I'm working on a way for us to specify folder where resources are located and load them from there. This is because when you run the app in debug mode in IntelliJ, you don't have access to the `data` folder as if it was running a release, so there appeared to be a few hacks in place to overcome this. 
Unfortunately, as there are some many places that resources are used, and used in various ways, its no easy task to change it all up. 

Are you getting errors due to this new change?

**Comment by schwabdidier** [comment]
oh I see ! 

In fact, a dutch mum sent me new translations for her language and I was lost. So, for now, if I modify the cvs file of translations, will it be updated on GitHub ?

**Comment by Tohaker** [comment]
Well, if you pull the latest master, and navigate to `gazeplay/src/main/resources/data/multilinguism/multilinguism.csv` and make the changes, you can indeed commit it to Git. The release build is set to take those resources and create a `data` folder still, so it will be like nothing changed.
When I find the time to continue with my investigation (I'm trying out the reflections API) then this should all still work, but locations in a release will probably change.

**Comment by Tohaker** [comment]
@schwabdidier Can this issue be closed now?
