### ISSUE TITLE
Work on game categories

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#904]
I began some reflexions about this. I will add a point about that here for feedback.

**Comment by kuhlkrein** [comment]
@schwabdidier 
In order to have approximatly the same number of game in each category I did this:

**Recherche et observation:**
Trouver Les Différences
Où est cet animal
Où est ce nombre
Où est cette couleur
Où est cette lettre
Où est-ce
Trouve les Drapeaux
Trouvez l’intru
Cartes à gratter
Blocs
Identifiez la lettre

**Memoire et attention:**
Mémory ouvert
Mémory ouvert (lettres)
mémory ouvert (nombres)
Mémory
Mémory (lettres)
Mémory (nombres)
Gobelet Pass Pass
La Fabrique à Gateaux
Ordre

**Utilitaires et Analyses:**
Gribouille
MediaPlayer
Coloriages
Piano
Lecteur Vidéo avec retour
Dés
Grille de Vidéos
J’ai un biboule !
La pièce

**Jeux de plateau:**
Jeu de l’oie
Jeu de la taupe
Jeu de taquin
Labyrinthe
Petits chevaux
Petits chevaux simplifiés
RushHour

**Apprentissage et eveil**
Ferme
Savane
Jungle
Appprends les Maths : Additions
Appprends les Maths : Soustractions
Appprends les Maths : Multiplications
Appprends les Maths : Divisions
Appprends les Maths : Toutes opérations
Potions Magiques
Cartes magiques

**Reflexe et precision:**
Biboule Jump
Bulles colorées
Bulles Portrait
Diviseur
La course des grenouilles
Lapins
Ninja !
Robots
Space Game
Tartes à la crème
Biboule

What do you think ?

**Comment by kuhlkrein** [comment]
@schwabdidier

**Comment by schwabdidier** [comment]
Why don't you use abilities mentionned in gazeplay article ?

**Comment by kuhlkrein** [comment]
Ah yes sorry I forgot about it, it is action-reaction, selection, and memorization skills then @schwabdidier ? Actually, I think that with the new games now we are maybe training more skills like in "apprends les maths" or in "jeu de taquin"

**Comment by kuhlkrein** [comment]
I tried to stick to the original categories here:

[Catégories.pdf](https://github.com/GazePlay/GazePlay/files/4052907/Categories.pdf)

**Comment by kuhlkrein** [comment]
For now we have the categories:
ACTION_REACTION | SELECTION | MEMORIZATION | LOGIC | CREATIVITY | UTILITY

The new categories should be:

ACTION_REACTION | SELECTION | MEMORIZATION |  | LOGIC_MATHS |
 MULTIMEDIA (or still _UTILITY_) | LITTERACY

using these category lists:

[Catégories.pdf](https://github.com/GazePlay/GazePlay/files/4071127/Categories.pdf)

@schwabdidier doest it look good for you ?

**Comment by kuhlkrein** [comment]
MULTIMEDIA is a mix between UTILITY and CREATIVITY in order to stick to the article description

**Comment by schwabdidier** [comment]
yes !
