### ISSUE TITLE
New game

### ISSUE THREAD

**Issue by schwabdidier** [GazePlay/GazePlay#938]
Based on "where is it" game : What is the bigger ? What is the smaller ?

For instance with balls, people,...

**Comment by YannRobert** [comment]
We should create a file  
that provides the Question 
and the list of images, along with the correct answer(s)

So that you don't have to create a new game 
and so that you can provide a way for parents to create new games

Parents will just have to create a new directory with this file
and the other resources files (images, correct anwsers, ...)
to create a new game variant

**Comment by schwabdidier** [comment]
Yes, like the White is it game
